---
  - name: Upload tar.gz Kibana from remote URL
    get_url:
      url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      mode: 0755
      timeout: 60
      force: true
      validate_certs: false
    register: get_kibana
    until: get_kibana is succeeded
    tags: elastic
  - name: Create directrory for Kibana
    file:
      state: directory
      path: "{{ kibana_home }}"
    tags: elastic
  - name: Extract Kibana in the installation directory
    become: false
    unarchive:
      copy: false
      src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "{{ kibana_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ elastic_home }}/bin/kibana"
    tags:
      - elastic
  - name: Set environment Kibana
    become: true
    template:
      src: templates/kib.sh.j2
      dest: /etc/profile.d/kib.sh
    tags: elastic
